#!/bin/sh
#
# chkconfig: 345 90 15
# description: GW

# Source function library.
. /etc/init.d/functions


BASE_DIR=/opt/h2db
PROC_NAME=org.h2.tools.Server
START_SH=startup.sh
#PROC_OPT="-b -r"
END_SH=shutdown.sh


PIDFILE=/var/run/H2DB.pid
LOCKFILE=/var/lock/subsys/H2DB

start(){
  #
  # Start H2 database
  #

  echo -n "Starting H2 database: "
  if [ -e $LOCKFILE ]; then
    echo "H2 database is already running!"
    echo_failure
    exit 1
  else
    cd $BASE_DIR/bin
    /bin/sh ./$START_SH $PROC_OPT > /dev/null 2>&1  &
    sleep 3
    ret=$?
    if [ $ret -eq 0 ]; then
      echo_success
      touch $LOCKFILE
    else
      echo_failure
    fi
  fi

  echo
}

stop(){
  #
  # Stop H2 database
  #
  echo -n "Shutting down H2 database: "

   /bin/sh ./$END_SH > /dev/null 2>&1  &
   ps -efwwwwwwwwww | grep $PROC_NAME | awk '{print "kill -9",$2}' | sh > /dev/null 2>&1
#  java_num=`ps aux | grep $PROC_NAME | grep -v grep | wc -l`
#  if [ $java_num -eq 1 ]; then
#    pidof java | xargs kill -9
#  fi

  echo_success
  rm -f $LOCKFILE
  echo
}

case "$1" in
  start)
    start
    ;;

  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    if [ -e $LOCKFILE ]; then
      echo "H2 database is running!"
    else
      echo "H2 database is stopping!"
    fi
    ;;
  *)
    echo $"Usage $0 {start|stop|restart|status}"
    exit 1;;
esac

